# Generated by Django 4.2.6 on 2023-10-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
    ]
