# Generated by Django 4.2.6 on 2023-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_comentario_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='data',
            new_name='data_hora',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='noticia',
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='url_noticia',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
